use_frameworks!

platform :ios, '10.0'

target 'LNVideoModule_Example' do
  pod 'LNVideoModule', :path => '../'

  pod 'SDWebImage', '5.9.5'
  pod 'Masonry'
  pod 'CocoaAsyncSocket'
  pod 'Aspects'
  pod 'YYKit'

  pod 'LNModuleCore', :path => '../../LNModuleCore'
  pod 'LNModuleProtocol', :path => '../../LNModuleProtocol'
  pod 'LNCommonKit', :path => '../../LNCommonKit'
  
  
  target 'LNVideoModule_Tests' do
    inherit! :search_paths

    
  end
end
