use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/LNOrganization/LNSpec.git'

platform :ios, '10.0'

target 'LNVideoModule_Example' do
  pod 'LNVideoModule', :path => '../'


#  pod 'LNModuleCore', :path => '../../LNModuleCore'
#  pod 'LNModuleProtocol', :path => '../../LNModuleProtocol'
#  pod 'LNCommonKit', :path => '../../LNCommonKit'
#
  
  target 'LNVideoModule_Tests' do
    inherit! :search_paths

    
  end
end
